In [1]:
import os
from pathlib import Path
# Change cwd to the project root (parent of 'notebooks/')
os.chdir(Path.cwd().parent)
Path.cwd()

PosixPath('/Users/jbrandt/code/birddog')

In [2]:
from birddog.logging import ServiceLogger
from datetime import datetime, timedelta, UTC
import pandas as pd

In [3]:
logger = ServiceLogger.get_logger()

In [4]:
now = datetime.now(UTC)
delta = timedelta(days=1)
df = logger.load_logs(now - delta, now)

In [5]:
df

,id,timestamp,resource,method,path,size,duration
0,1,2025-09-07 22:17:00.250527,local_fs,load,page_update_manager.json,244,0
1,2,2025-09-07 22:17:00.252186,KVStore,get_all,TranslationManager:in_process,2,0
2,3,2025-09-07 22:17:00.253148,StringQueue,peek,TranslationManager:pending,2,0
3,4,2025-09-07 22:17:00.917646,local_fs,load,page_update_manager.json,244,0
4,5,2025-09-07 22:17:00.920219,KVStore,get_all,TranslationManager:in_process,2,1
...,...,...,...,...,...,...,...
9326,9327,2025-09-08 17:01:00.276164,StringQueue,peek,TranslationManager:pending,2,3
9327,9328,2025-09-08 17:01:05.284086,KVStore,get_all,TranslationManager:in_process,2,1
9328,9329,2025-09-08 17:01:05.287944,StringQueue,peek,TranslationManager:pending,2,0
9329,9330,2025-09-08 17:01:10.294605,KVStore,get_all,TranslationManager:in_process,2,1
9330,9331,2025-09-08 17:01:10.303849,StringQueue,peek,TranslationManager:pending,2,2

In [7]:
ServiceLogger.summarize_service_usage(df, sample_interval_minutes=24*60)

,resource,method,count,cumulative_size,cumulative_duration,count_per_minute,size_per_minute
0,DummyTranslator,translate,105,105483,0,0.072917,73.252083
1,KVStore,count,236,0,0,0.163889,0.000000
2,KVStore,get,231,41419,21,0.160417,28.763194
3,KVStore,get_all,3314,442955,3217,2.301389,307.607639
4,KVStore,insert,697,1056309,278,0.484028,733.547917
5,KVStore,remove,235,6777,176,0.163194,4.706250
6,KVStore,remove_all,4,0,3,0.002778,0.000000
7,ModDateStore,batch_store_updates,8,2015,24,0.005556,1.399306
8,ModDateStore,get_newer_updates,66,34834769,2143,0.045833,24190.811806
9,ModDateStore,query_by_prefix,72,12255570,377,0.050000,8510.812500
10,StringQueue,append,4,739882,6,0.002778,513.806944
11,StringQueue,peek,3756,22183,1236,2.608333,15.404861
12,StringQueue,pop,240,741748,95,0.166667,515.102778
13,local_fs,load,179,33679412,140,0.124306,23388.480556
14,local_fs,save,184,27971869,24,0.127778,19424.909028

In [ ]:
s=summarize_service_log(df, by="resource")

In [ ]:
val = s.loc[s["resource"].eq("StringQueue"), "cumulative_size"]
cumulative = int(val.iloc[0]) if not val.empty else 0
cumulative

In [ ]:
v = cumulative_size

In [ ]:
td=timedelta(**v)

In [ ]:
s

In [ ]:
td.min

In [ ]:
td

In [ ]:
td.total_seconds()

In [ ]:
delta.total_seconds()

In [ ]:
summarize_service_log(df)

In [ ]:
    grouped = (
        tmp.groupby(["resource", "method"], dropna=False, observed=True)
           .agg(
               count=("resource", "size"),                 # number of rows in group
               cumulative_size=("size", "sum"),            # bytes
               cumulative_duration=("duration", "sum"),    # seconds
           )
           .reset_index()
    )